import http.server
import os, re, yaml, json
import http

HEADER = """<head>
  <title> Nick Felten's personal site </title>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Nick Felten">
  <meta name="keywords" content="">
  <!--<link rel="icon" type="image/x-icon" href="/images/favicon.ico">-->

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Space+Mono">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="/style/stylesheet.css"></style>

  <script src="/4040/vocabulary_data.js"></script>
  <script src="/Portfolio/data.js"></script>
  <script src="/source.js"></script>
</head>"""

def change_header(filepath: str):
    print(f"modifying {filepath}")
    with open(filepath, "r") as f:
        str = f.read()
    
    #print(re.findall(r"<head>(.|\n)*<\/head>", str))
    str = re.sub(r"<head>(.|\n)*<\/head>", HEADER, str)
    #str = str.replace("<body", '<body onload="on_load();"')

    with open(filepath, "w") as f:
        f.write(str)


def convert_vocabulary():
    with open("4040/vocabulary.yaml", "r") as f:
        voc = yaml.safe_load(f)

    with open("4040/vocabulary_data.js", "w") as f:
        f.write("// Auto-generated by builder.py \n")
        f.write("let vocabulary_data = ")
        json.dump(voc, f)
        f.write(";")


def plug_headers():
    for root, dirs, files in os.walk("."):
        for filename in files:
            if filename.endswith(".html"):
                change_header(os.path.join(root, filename))


def server():
    server = http.server.HTTPServer(("127.0.0.1", 8000), http.server.SimpleHTTPRequestHandler)
    server.serve_forever()


if __name__ == "__main__":
    convert_vocabulary()
    plug_headers()
    server()
